### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by heliohead** [azukiapp/azk#171]
I just start to write a bash completion for azk, on https://gist.github.com/heliohead/d422d315cd6b583038b4
 But all agent commands start with st (start,status,stop) and 2 commands with sta.
So, how about to change agent command names to quit, or something like that.
I am a very lazy guy and tap one letter and tab would be great,

Just thoughts.
Tks.
#palpiteiro

**Comment by gullitmiranda** [comment]
@heliohead 
Since we changed the CLI adding the `cli-router` (with support to [docopt](docopt.org)) in PR https://github.com/azukiapp/azk/pull/412, it'll be possible to add support to bash completion.

Using the script [docopt-completion](https://github.com/Infinidat/infi.docopt_completion), we can generate the autocomplete wordlist, both for `zsh` as for `bash`. Those scripts are available at `shared/completions/`.

The only remaining step is to install the scripts.

![screen shot 2015-06-04 at 01 45 37](https://cloud.githubusercontent.com/assets/2034678/8013022/29c93c9c-0b9c-11e5-830e-1d378093f0ff.png)

**Comment by heliohead** [comment]
Awesome 🎉 🎊 🎈

You need to install fonts  >.<

hehe,

Closing issue... in  3... 2....

**Comment by gullitmiranda** [comment]
:D
