### ISSUE TITLE
Azk init doesn't recognise the correct rails version

### ISSUE THREAD

**Issue by lucasfais** [azukiapp/azk#224]
I created a new rails app as shown below. Note the rails version is **4.2**.

```shell
$ azk shell --image rails --shell /bin/bash
root@c111ccd0c87e:/azk/azk-labs# rails -v
Rails 4.2.0
root@c111ccd0c87e:/azk/azk-labs# rails new rails42
      create
      create  README.rdoc
      create  Rakefile
      create  config.ru
...
$ exit
```

Now I used the `azk init` command to generate the `Azkfile.js`.

```shell
$ cd rails42
$ azk init
```

The problem is that `Azkfile.js` was generated using rails **4.1**.

```javascript
systems({
  rails42: {
    // Dependent systems
    depends: [],
    // More images:  http://images.azk.io
    image: "rails:4.1",
...
```

So, when I tried to run `azk start`, it started to download the `rails:4.1` image...

Anyway, the `azk init` needs to be improved to recognise the correct rails version.

**Comment by gullitmiranda** [comment]
My reccomendation:

```
$ azk shell --image azukiapp/ruby --shell /bin/bash
# gem install rails -v 4.2.0
# rails -v
Rails 4.2.0
# rails new rails42
# exit
$ cd rails42
```

I do not particularly like the concept of using an image with rails already installed. In rails community, update framework versions during the project development is something trivial and common.

The rails is just another dependence and not a runtime. When provisioning runs, the rails are installed as defined in Gemfile.

If used an image with the rails already installed, the image will have two versions of rails which may end up providing some problems. Mainly around the deployment, it will be only installed the version that really matters.

Another motivation for this approach is that the user can choose the version that will use to project generation, because each version has its peculiarities.

**Comment by lucasfais** [comment]
I agree with you, but even doing your suggested steps, once the *rails* app was created, executing `azk init` it will put the wrong image in the `Azkfile.js`. The app is *rails 4.2* and `azk` recognise it as a *4.1* app.

**1. we can fix that;** or
**2. we can change `azk init` behaviour to suggest a ruby image instead a rails image like you suggested.**

Anyway, in the second approach, it will need use some evidences to suggest the correct *ruby* version. If the *ruby* version is locked in `Gemfile` its easy, but if not, one possibility is to look at the *rails* version and suggest a *ruby* version that is compatible with that *rails* version. 

We need to be careful here because the `azk init` job will become a little more complex.

**Comment by gullitmiranda** [comment]
I am inclined the second solution for the same reason noted above.

Create a image rails and suggestion for each version would be very complex and something unnecessary since the rails is installed during the 'bundle install`, whether or not a version of rails already installed.
