### ISSUE TITLE
Add option to get the homedir(HOME)

### ISSUE THREAD

**Issue by robsonpeixoto** [azukiapp/azk#352]
When we are working with maven is very useful create reuse the `$HOME/.m2` directory, like it:

```javascript
systems({
  'myapp': {
    depends: [],
    image: {docker: "java:7"},
    provision: [
      "curl http://mirror.nbtelecom.com.br/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz -o /tmp/apache-maven-3.2.5-bin.tar.gz",
      "tar xzfv /tmp/apache-maven-3.2.5-bin.tar.gz -C /opt",
      "ln -vs /opt/apache-maven-* /opt/maven",
      "/opt/maven/bin/mvn package -DskitTests"
    ],
    command: "target/appassembler/bin/myapp",
    workdir: "/root/#{manifest.dir}",
    mounts: {
      "/root/#{manifest.dir}": path('.'),
      "/root/.m2": path('$HOME/.m2')
    },
    http: {
      domains: ["#{system.name}.#{azk.default_domain}"]
    },
    envs: {
      PORT: "8000"
    }
  })
```

But it can be useful to reuse cache for others solutions like Ivy, pip, ...

**Comment by nuxlli** [comment]
@robsonpeixoto it is already possible to read the content of your environment variables and use it in Azkfile.js. Try something like this:

```js
// ...
mounts: {
  "/root/#{manifest.dir}": path('.'),
  "/root/.m2": path(env.HOME + '/.m2')
},
// ...
```

We are looking into to expand it to support "templates". Something like `#{env.HOME}/.m2` which will make `Azkfile.js`'s API more concise.

Beyond this I'd like to make some observations about your `Azkfile.js` if you allow me:

### Provision

*Provision* session is available to run pre-execution commands for things like data migration, dumps loading or to install dependencies as you did but one important thing about what is being executed there: only things recorded in mountings like "persistent" will be kept for future usage.

That said, `maven` installation could even be placed inside `/opt` if `/opt` is added to `mounts` but the ideal solution is to prepare your system image to contain `maven`.
You don't need to create an image on Docker Registry to use it. You can simple use your `Dockerfile` locally as above:

```Dockerfile
# Dockerfile
FROM node:0.12.0

ADD http://mirror.nbtelecom.com.br/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz /opt
RUN ln -vs /opt/apache-maven-* /opt/maven
```

Then you can set up your `Azkfile.js` as above to use it:

```js
systems({
  'myapp': {
    depends: [],
    image: { dockerfile: "./Dockerfile" },
    provision: [
      "/opt/maven/bin/mvn package -DskitTests"
    ],
    // ...
  }
});
```

### Ports

If I correctly understood your project it will run a http app on port `8000`. I believe that is why you added `env: { PORT: 8000 }`.

For the loading balancer work correctly you will need to add one more entry:

```js
// ...
ports: {
  http: "8000"
}
```

But this could be done directly if you modify your application to ask for the `HTTP_PORT` environment variable instead of `PORT` because once you add `http: { domains: /*...*/ }`, to a system of `Azkfile.js`, `azk` will automatically add `ports.http` and you have `HTTP_PORT` (with default value of `5000`) to run your application and allow that loading balancer to "find your application".

**Comment by robsonpeixoto** [comment]
Thanks a lot @nuxlli 
I'm using `PORT` because a lot of PASS(tsuru, heroku, ...) are using it.
