### ISSUE TITLE
azk works but the app is very slow

### ISSUE THREAD

**Issue by Lucasosf** [azukiapp/azk#379]
Azk works but the app is very slow running on rails server thin.

Can you help me?

That is the sync folder problem, right?

**Comment by nuxlli** [comment]
@Lucasosf that's right,

a while ago we made some big changes to `azk`'s code, with the goal of replacing the use of `nfs` as the file sharing between host and guest to VirtualBox's native file sharing system. That can be seen in the #282 PR.

That solved a good amount of development cases, but we have observed that for applications that have a lot of files, like complex rails applications, the behaviour of the file sharing system can still be bad.

We made some performance tests, and also analyzed tests made by people from Vagrant about the processes and solutions involved regarding this issue. In the end we found out that, at the moment, there's no "excellent" solution available.

Right now we're going to work on a temporary solution, probably using "rsync", which might help in your case, while we work on a more definitive solution.

**Comment by dynaum** [comment]
@Lucasosf if you have a lot of assets like me you can try to turn off assets.debug.
http://guides.rubyonrails.org/asset_pipeline.html#turning-debugging-off

Works for me.

**Comment by Lucasosf** [comment]
Thank you @nuxlli I will wait for it.

Thank you @dynaum, but didn't work for me =/

**Comment by nuxlli** [comment]
#### Support to file sync in `mounts`

Today, systems described in an Azkfile.js support a kind of mounting that allows us to share local (or project) folders with a container, known as `path`:

It's a local path (in the host machine) that's "mounted" to a path inside the container. In this method, the overall performance is better in Linux (without VM) than in MacOS X, that has its performance decreased by limitations of Virtual Box file sharing system.

Despite of our efforts to optimize it, in cases which there are too many files in a project (e.g. Rails app with a lot of assets), the poor performance of file sharing system becomes clear and even a block to the usage of azk.

The alternative solutions can be:

  - Write a new file sharing system: focused on the file exchange between the host machine and a virtualized guest machine. In this system, the overhead to deal with cryptography or information exchange about permissions would be removed since the network between host and guest can be considered secure. Besides that, there are specific optimizations that aren't possible in file sharing systems designed to networks, like NFS and/or SMB/CIFS. Actually, this work was started in https://github.com/azukiapp/azkfs. But though the initiative had shown itself promising and maybe it's the best alternative in the future, it demands amount of work and research time that's unavailable in this moment of the project;

  - File sync system: Different from a file sharing system, a file sync system uses a tool like [rsync](https://rsync.samba.org) or [unison](http://www.cis.upenn.edu/~bcpierce/unison/) to sync files and folders between two machines (or between two folders, in the Linux case which doesn't uses a VM). This alternative has shown itself functional in [Vagrant](http://docs.vagrantup.com/v2/synced-folders/rsync.html) and could be a good option in the short term, despite of some limitations.

#### Rsync

The main limitations in using a file sync based system are:

  - Less transparency and more interference from user: Today, in order to share a folder or file, the user has just to indicate the source and destination paths and `azk` does all the rest. In a file sync based system, it's needed to point the exceptions to avoid sync'ing unnecessary files which would make the process slower. In the other hand, this could generate more details to Azkfile.js which would help in the packaging and deploying processes;
  - The `azk` start process to a fresh system could be really slow, since all the files would have to be sync'ed before the containers could be started (need more tests);
  - Once the system is running, `azk` would need to run a "daemon" to wait for modifications and sync the watched files;
  - Two-way sync is almost "impossible", despite of solutions like [unison](http://www.cis.upenn.edu/~bcpierce/unison/) offer support to this feature, its implementation isn't trivial and can generate inconsistences and corrupting `azk` user's files.

**Comment by nuxlli** [comment]
One more reference: http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines
