### ISSUE TITLE
[Docker] Not clear message on connection failure with the docker.

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#441]
When I ran the 'azk agent start` command and he was not able to connect with the Docker, the error shown was ugly.

```shell
$ azk agent start
```

![image](https://cloud.githubusercontent.com/assets/2034678/7945347/8db0e4e2-0946-11e5-8a98-19053b85a64c.png)

**Comment by saitodisse** [comment]
I believe because (https://github.com/azukiapp/azk/blob/07ee52476c/src%2Futils%2Fpromises.js#L4-L11) `Unhandled Rejection` are caught now, will no longer see this ugly errors. I ran here and got this message:

![image](https://cloud.githubusercontent.com/assets/155953/8235233/37988eca-15b7-11e5-8682-19a1abc78acb.png)

Could you test again with the current master @gullitmiranda?

**Comment by saitodisse** [comment]
I've made another test.

1) forcing agent error (src/agent/balancer.js):

```js
  _waitDocker(retry = 10) {
    var docker_host = config("docker:host");
    var promise = net.waitService(docker_host, retry, { timeout: 2000, context: "balancer" });
    return promise.then((success) => {
      //FIXME: FORCED ERROR
      throw new AgentStartError(t('errors.connect_docker_unavailable'));
      // if (!success) {
      //   throw new AgentStartError(t('errors.connect_docker_unavailable'));
      // }
      // return success;
    });
  },
```

2) I have activated the azk VM on linux:

```sh
sudo rm -rf /etc/resolver/dev.azk.io
export AZK_USE_VM=true
```

3) `azk agent start` error message:

![image](https://cloud.githubusercontent.com/assets/155953/8255558/12f5c32e-1677-11e5-9cee-53617d4e9ef2.png)

----------------

I believe we can close this Issue, @gullitmiranda .
