### ISSUE TITLE
`azk restart` fails when system is not already started

### ISSUE THREAD

**Issue by slobo** [azukiapp/azk#449]
If a system is not already running, issuing restart gives confusing messages and doesn't bring the system up. 
```
$ azk restart drupal
azk: System `drupal` not running
azk: System `drupal` already started
```
One could argue that ``azk restart`` should fail on a system that is not running, but then the message should be fixed to not include the 'already started' bit.

**Comment by gullitmiranda** [comment]
@slobo,

What is the value of the option `scalable` this system?

**Comment by slobo** [comment]
``scalable: {"default": 1}``

**Comment by slobo** [comment]
Just tested with a system that doesn't have a ``scalable`` key - and same thing happens.

**Comment by gullitmiranda** [comment]
You're right, @slobo. This issue is related to the 'intelligence' added to `azk` couple versions ago.
Current `restart` logic saves the current state of instances and restore it after start.

While the [global status](https://github.com/azukiapp/azk/issues/325) feature isn't implemented, I think the best is to rollback to previous implementation, where `restart` means `stop` + `start`, i.e. the final state is the one defined in Azkfile.js.
