### ISSUE TITLE
Ubuntu >= 15 with latest docker version

### ISSUE THREAD

**Issue by renanmpimentel** [azukiapp/azk#507]
When upgrading to version 0.14.6, AZK automatically installs the latest version of docker. AZK does not always works 100% with the latest docker version. I think it would be better to leave a fixed version, instead of taking the last update.

```
Selecting previously unselected package docker-engine. 
Preparing to unpack .../docker-engine_1.8.1-0~vivid_amd64.deb ... 
Unpacking docker-engine (1.8.1-0~vivid) ...
```

**Comment by nuxlli** [comment]
@renanmpimentel I'm sorry for this.

In azk latest version (v0.14.6), we've added a Docker API version lock, as this PR: https://github.com/azukiapp/azk/pull/499. However, it seems this won't be enough because even Docker supporting older API versions, it doesn't support the features from an older Docker version.

We're working in a new azk version (v0.15.0) in which we're going to add a Docker version lock and features to support Docker 1.7 or newer.

**Comment by renanmpimentel** [comment]
But the AZK will persist with the behavior of installing the latest version of docker?
Because from what I noticed, the version (v0.14.6) does not need docker installed on the machine.

**Comment by nuxlli** [comment]
@renanmpimentel actually it does. Docker has changed its default repo and package name from `lxc-docker` to `docker-engine`, and both deb and rpm packages require it.

Since in this new Docker repo only the latest Docker version is available, we have assumed the behavior you described.

**Comment by renanmpimentel** [comment]
Nice! :+1:
